kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao_openam_proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao_openam_proxy/poao_openam_proxy:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://app.adeo.no/poao-openam-proxy
    - https://app.intern.nav.no/poao-openam-proxy
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  envFrom:
    - configmap: pto-config
  env:
    - name: MULIGHETSROMMET_API_URL
      value: https://mulighetsrommet-api.intern.nav.no
