kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-openam-proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-openam-proxy/poao-openam-proxy:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://app.dev.adeo.no/poao-openam-proxy
    - https://app-q1.dev.adeo.no/poao-openam-proxy
    - https://app-q1.adeo.no/poao-openam-proxy
    - https://app.dev.intern.nav.no/poao-openam-proxy
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  envFrom:
    - configmap: pto-config
  env:
    - name: MULIGHETSROMMET_API_URL
      value: https://mulighetsrommet-api.dev.intern.nav.no
    - name: MULIGHETSROMMET_SCOPE
      value: api://dev-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
